firstdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('lunch/', views.lunch),
    path('hello/<str:name>/', views.hello),
    path('cube/<int:num>/', views.cube),
    path('todos/', include('secondapp.urls')),
]

secondapp/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index),
    path('new/',views.new),
    path('create/',views.create),
    path('<int:id>/', views.read),
    path('todo_create/',views.todo_create),
    path('<int:id>/update', views.update, name="update"),
    path('<int:id>/delete', views.delete, name="delete"),
]

firstapp/models.py
from django.db import models

# Create your models here.

secondapp/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length = 50)
    deadline = models.DateField()
    
    def __str__(self):
        return self.title

firstapp/views.py
from django.shortcuts import render
import random

# Create your views here.
def index(request):
    return render(request, 'index.html')
def lunch(request):
    menu_list = ["20층", "김카", "굶음"]
    pick= random.choice(menu_list)
    return render(request, 'lunch.html', {'lunch':pick})
def hello(request, name):
    return render(request,'hello.html', {'name':name})
def cube(request, num):
    multi = num**3
    return render(request, 'cube.html', {'multi': multi})

secondapp/views.py
from django.shortcuts import render, redirect
from secondapp.models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    return render(request, 'secondapp/index.html',{'todos':todos})
def new(request):
    return render(request, 'secondapp/new.html')

def create(request):
    title = request.POST.get('title')
    deadline = request.POST.get('deadline')
    todo = Todo(title=title, deadline=deadline)
    todo.save()
    return redirect('/todos/')

def read(request, id):
    todo = Todo.objects.get(id=id)
    return render(request, 'secondapp/read.html', {'todo':todo})
    
def todo_create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        deadline = request.POST.get('deadline')
        Todo.objects.create(title=title, deadline=deadline)
        return redirect('/todos/')
    else:
        return render(request, 'secondapp/todo_create.html')

def update(request, id):
    todo = Todo.objects.get(id = id)
    if request.method == "POST":
        todo.title = request.POST.get('title')
        todo.deadline = request.POST.get('deadline')
        todo.save()
        return redirect('/todos/')
    else:
        deadline = todo.deadline.strftime("%Y-%m-%d")
        # deadline = "{}-{}-{}".format(todo.deadline.year,todo.deadline.month, todo.deadline.day)
        return render(request, 'secondapp/update.html', {'todo':todo, 'deadline':deadline})

def delete(request, id):
    todo = Todo.objects.get(id = id)
    todo.delete()
    return redirect('/todos/')

firstapp/templates/cube.html
{{multi}}

firstapp/templates/hello.html
{{name}}

firstapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    halla!
    
</body>
</html>

firstapp/templates/lunch.html
{{lunch}}

secondapp/templates/secondapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="/todos/new">글 작 성</a>
    <a href="/todos/todo_create">합 쳐 진 로 직</a>
    {% block body_block %}
    {% endblock %}
</body>
</html>

secondapp/templates/secondapp/index.html
{% extends 'secondapp/base.html' %}
{% block body_block %}
    <h1>This is SecondApp's index</h1>
    {% for todo in todos %}
        {{todo.title}}
        {{todo.deadline}}
        <a href="/todos/{{todo.id}}">글 보 기</a>
    {% endfor %}
{% endblock %}

secondapp/templates/secondapp/new.html
{% extends 'todo/base.html' %}
{% block body_block %}
<form action = "/secondapp/new">
    <input type="text" name="title"/>
    <input type="date" name="title"/>
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

secondapp/templates/secondapp/read.html
{% extends 'secondapp/base.html' %}

{% block body_block %}
    <h1>{{todo.title}}</h1>
    <h4>{{todo.deadline}}</h4>
    <a href="/todos/{{todo.id}}/update">수 정</a>
    <!--<a href="{% url 'todo:update' id=todo.id %}">또다른 수정</a>-->
    <a href="/todos/{{todo.id}}/delete">삭 제</a>
{% endblock %}

secondapp/templates/secondapp/todo_create.html
{% extends 'secondapp/base.html' %}

{% block body_block %}
<form action = "/todos/todo_create/" method = "POST">
    {%csrf_token%}
    <input type="text" name="title"/>
    <input type="date" name="deadline"/>
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

secondapp/templates/secondapp/update.html
{% extends 'secondapp/base.html' %}
{% block body_block %}
<form action = "/todos/{{todo.id}}/update" method="post">
    {% csrf_token %}
    <input type="text" name="title", value="{{todo.title}}"/>
    <input type="date" name="deadline" value="{{deadline}}"/>
    <input type="submit" value="Submit"/>
</form>
{% endblock %}